

server:
  error:
    include-exception: true
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

file:
  dir: /Users/ichan-uadmin/Desktop/Propose/photo/


spring:
  application:
    name: Propose
  datasource:
    url: jdbc:mysql://localhost:3306/diary
    username: root
    password: a123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace



